module.exports = {
    user: 'user',
    item_type: 'item_type',
    subnationalDivision: 'subnationalDivision',
    country: 'country',
    shape: 'shape',
    inventory_location: 'inventory_location',
    address: 'address',
    company: 'company',
    company_type: 'company_type',
    size: 'size',
    item: 'item',
    item_info: 'item_info',
    item_image: 'item_image',
    related_item: 'related_item',
};